# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apiannedocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://apiannedocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aa0b2cff2e6c432caffadbce93c6ea87 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_838af9c94d1e4a59bba9478856aa3d08 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: apiannedocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa0b2cff2e6c432caffadbce93c6ea87 }}/apiannedocker/fast:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apiannedocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fc41eefd6da640769e0b8c8481f118ea }}
        images: 'apiannedocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa0b2cff2e6c432caffadbce93c6ea87 }}/apiannedocker/fast:${{ github.sha }}'