# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apiannedocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://apiannedocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b5be7aa2dd1d4ff2865818c8085b91eb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a9b7de8f637f4cbb8b3ce7900b7e2bbb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: apiannedocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b5be7aa2dd1d4ff2865818c8085b91eb }}/fast:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apiannedocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_168e62bec28040b79c492c7f4170bd16 }}
        images: 'apiannedocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b5be7aa2dd1d4ff2865818c8085b91eb }}/fast:${{ github.sha }}'